name: residents
description: Frontend for residents app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Default icons asset for Cupertino widgets based on Apple styled icons
  cupertino_icons: ^1.0.2
  # Library used for making HTTP requests
  http: ^0.13.4
  # Plugin for integrating Google Maps in mobile application
  google_maps_flutter: ^2.1.8
  # Package for getting polyline points on google map
  flutter_polyline_points: ^1.0.0

  # Customizes default white native splash screen
  flutter_native_splash: ^2.2.3+1
  # Dropdown widget containing extra customizable features
  dropdown_button2: ^1.6.2
  # Plugin for selecting gallery images and taking new camera pictures
  image_picker: ^0.8.5+3
  # Plugin for cropping images
  image_cropper: ^2.0.3
  # State management library with route management and dependency injection
  get: ^4.6.5
  # Plugin used to read and write app data preserved to the disk asynchronously
  shared_preferences: ^2.0.15
  # Package used to update app launcher icon
  flutter_launcher_icons: ^0.9.2
  image: ^3.2.0
  http_parser: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "residents_launcher"
  ios: true
  image_path: "assets/icons/playstore_icon_wb.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/playstore_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/green-logo.png
    - assets/images/green-logo2.jpg
    - assets/images/black-logo.png
    - assets/images/relai-green-logo.png
    - assets/images/relai-green-text.png
    - assets/images/relai-black-text.png
    - assets/images/relai-white-text.png
    - assets/images/EZ.bmp
    - assets/images/store.bmp
    - assets/images/arrow.bmp
    - assets/images/default-avatar.png

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Black.ttf
          weight: 900
        - asset: assets/fonts/Barlow-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Barlow-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Barlow-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Barlow-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Barlow-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Barlow-Regular.ttf
          weight: 400
        - asset: assets/fonts/Barlow-Italic.ttf
          style: italic
        - asset: assets/fonts/Barlow-Light.ttf
          weight: 300
        - asset: assets/fonts/Barlow-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Barlow-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Barlow-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Barlow-Thin.ttf
          weight: 100
        - asset: assets/fonts/Barlow-ThinItalic.ttf
          weight: 100
