# Generated by Django 3.2.14 on 2022-08-09 08:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_sprinter', models.BooleanField(default=False)),
                ('is_resident', models.BooleanField(default=False)),
                ('is_shopper', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=60, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=60, null=True, verbose_name='last name')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='phone')),
                ('avatar', models.ImageField(blank=True, default='avatars/default/default-avatar.png', null=True, upload_to='avatars/users/')),
                ('home_address', models.CharField(max_length=100, null=True, verbose_name='home address')),
                ('home_state', models.CharField(max_length=15, null=True, verbose_name='home state')),
                ('home_unit', models.CharField(max_length=15, null=True, verbose_name='home unit')),
                ('home_city', models.CharField(max_length=50, null=True, verbose_name='home city')),
                ('date_of_birth', models.DateField(default=datetime.date.today, max_length=8, verbose_name='date of birth')),
                ('mailing_address', models.CharField(max_length=100, null=True, verbose_name='mailing address')),
                ('mailing_unit', models.CharField(max_length=15, null=True, verbose_name='mailing unit')),
                ('mailing_city', models.CharField(max_length=50, null=True, verbose_name='mailing city')),
                ('mailing_state', models.CharField(max_length=15, null=True, verbose_name='mailing state')),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(0, 'sprinter'), (1, 'resident'), (2, 'shopper'), (3, 'admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Sprinter',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='account.account')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('avatar', models.ImageField(upload_to='avatars/')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='roles',
            field=models.ManyToManyField(to='account.Role'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
