# Generated by Django 3.2.14 on 2022-08-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'sprinter'), (2, 'resident'), (3, 'shopper'), (4, 'admin')], primary_key=True, serialize=False),
        ),
    ]
